### ISSUE TITLE
Could vibration function be added?

### ISSUE THREAD

**Issue by natlus2** [zwenergy/CPAK2040#1]
the possibility of adding vibration, using the rumble of a mobile phone for example.

I don't know if it would be possible to run memory pak and rumble pak at the same time, if it were not possible, you could alternate between modes.

**Comment by zwenergy** [comment]
It's difficult with the current simplicity of just using a single Pico, because there is not a single GPIO left to use to control a rumble motor. If I do a new version, which is not based on the Pico, but an own design around the RP2040, I could add this.
