### ISSUE TITLE
[HELP] 30 mempacks

### ISSUE THREAD

**Issue by davidxgames** [zwenergy/CPAK2040#4]
"I couldn't increase it to more than 15 mempacks. Is it possible to do so, or would that be the limit? I would like to have about 30. Could you help me?"

**Comment by zwenergy** [comment]
How exactly does your issue look like? For the USB functionality you'd need to adapt the FAT12 system, but the "pure" memory pack functionality should be working I think despite.

**Comment by davidxgames** [comment]
> How exactly does your issue look like? For the USB functionality you'd need to adapt the FAT12 system, but the "pure" memory pack functionality should be working I think despite.

It works perfectly for me, except I want to add more mempacks but I can only do it up to 15:

`'M', 'E', 'M', 'P', 'A', 'K', '1', '5', 'M', 'P', 'K', 0x20, 0x00, 0xC6, 0x52, 0x6D,
                0x65, 0x43, 0x65, 0x43, 0x00, 0x00, 0x88, 0x6D, 0x65, 0x43, 0x42, 0x00,
                0x00, 0x80, 0x00, 0x00, 

#define NRMEMPAKS 15`

But I can't add more, I even added a function so that if you quickly press the button twice it returns to the previous mempack.

I also added a second rp2040 to display the current mempack on a screen.

Could you tell me how to add more mempacks?

I don't speak English, I use Google Translate, so sorry.

edit: I understand, you're telling me that the 30 mempacks work on the console but I won't be able to see more than 15 when I connect to the PC?

**Comment by zwenergy** [comment]
> `'M', 'E', 'M', 'P', 'A', 'K', '1', '5', 'M', 'P', 'K', 0x20, 0x00, 0xC6, 0x52, 0x6D,
0x65, 0x43, 0x65, 0x43, 0x00, 0x00, 0x88, 0x6D, 0x65, 0x43, 0x42, 0x00,
0x00, 0x80, 0x00, 0x00,

You also would have to adjust the FAT12 table, not just the root directory. Maybe also parts of the boot sector, I'm not sure about the sizes I put there right now. If you don't speak English, it would be probably the best if you would search for something like "FAT12 file system" in your native language to find an overview, how it is structured. 

> edit: I understand, you're telling me that the 30 mempacks work on the console but I won't be able to see more than 15 when I connect to the PC?

Yes, I think if you only change the number of packs in main.c, it should still work on the console, but the regular USB storage view would be messed up.

**Comment by davidxgames** [comment]
> > `'M', 'E', 'M', 'P', 'A', 'K', '1', '5', 'M', 'P', 'K', 0x20, 0x00, 0xC6, 0x52, 0x6D, 
> > 0x65, 0x43, 0x65, 0x43, 0x00, 0x00, 0x88, 0x6D, 0x65, 0x43, 0x42, 0x00, 


Hello, thanks for responding. I already tried modifying the FAT12 system, but I can't get it to work. I managed to compile with the 30 mempacks without errors, but when I connect it to the PC, it says the drive needs to be formatted. The thing is, I don't know how to program; the little I know, I've learned by modifying existing code. Hopefully, one day you'll have time to add more mempacks. With 30, I think it would be enough to have a definitive N64 controller pack.

I will send you a video via the social network X so you can see how I implemented the display to indicate the current mempack.

**Comment by zwenergy** [comment]
Yeah, unfortunately it's not as simple as just adding more lines to the root directory part. The entries of the root directory part also point to the first sector of the file in the FAT table, so you would need to add sectors to the FAT and then set the right sector address in the newly added root directory entry.
